---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres
  namespace: immich
spec:
  encryptedData:
    password: AgAe9ZObXexAJIuqYcChsl/a2nalkgQl4ZMHRgCx6nPRSfo1zyXMjr1eSYynKTVO48lHn+ZHxBd2Jqld5Izb9KiOn2J3O8pTahqBObfdaUmTNx/G9g5P2XtiNBGu0PUkjM1kh35kYrUlsjkL39SLwGZBzW/GSTPveLgO5Fu1qK/18MEblNGb+EGgFfJk2UPePhke6pk+2CMLsD1I0krE8VYcnHG1vSO8ALL8DUGVo5dxhd3he9Ap/va0TmGJfPFRbt8sRgA8yAXGosFX7PmXF9JBI5ZUWC+JRDXEFHxBLvRIyWLGoyFYQYlsYfCwhl+jqzZ0kMh5+fFwAcbax5qcrCUe7JrfSu9DIvsHIg87D7g/2kJRYRy1ovyEG6N1IWo3PHmsHAghAVVo1szDqKEVoroaO9IUPhh684HKyKAq/pMROa7kqPjvZuAtnVqYmrWE0F7GF//IwZFD/aOLwluWn7Ps+T3K6LgSzVaJbS1t/bjNyEwsS3DU6SRkjm+TPcCT1qOOV0HR5v9tlZp1KvKisXxhLNsIjllClYKVWvN9DT2NLqgZ1rhKHdnm2es7IMkRdortIhqwER4o/dK/tXdubY4d8HPMmpdwEN4VVdJ5VK8GZTlTVF95pzJBJYy83ZklXYNi/Ja5ulhpONfFMtmoQTufiXXh3qc7KBqkKq4F3gBd2ywAxbkNpe4JZt/oOxYT0Xk3nnK2xueI714otR8HDC26TPl4SgYbjHiVYe5S44EezQ==
  template:
    metadata:
      name: immich-postgres
      namespace: immich
