# Operator oauth credentials. If set a Kubernetes Secret with the provided
# values will be created in the operator namespace. If unset a Secret named
# operator-oauth must be precreated or oauthSecretVolume needs to be adjusted.
# This block will be overridden by oauthSecretVolume, if set.
oauth:
  clientId: 
  clientSecret: 

# Secret volume.
# If set it defines the volume the oauth secrets will be mounted from.
# The volume needs to contain two files named `client_id` and `client_secret`.
# If unset the volume will reference the Secret named operator-oauth.
# This block will override the oauth block.
oauthSecretVolume: {}
  # csi:
  #   driver: secrets-store.csi.k8s.io
  #   readOnly: true
  #   volumeAttributes:
  #     secretProviderClass: tailscale-oauth
  #
  ## NAME is pre-defined!

installCRDs: true

operatorConfig:
  defaultTags:
    - "tag:k8s-operator"

  image:
    repository: tailscale/k8s-operator
    tag: ""
    digest: ""
    pullPolicy: Always
  logging: "info" # info, debug, dev
  hostname: "tailscale-operator"
  nodeSelector:
    kubernetes.io/os: linux

  resources: {}

proxyConfig:
  image:
    repository: tailscale/tailscale
    tag: ""
    digest: ""
  defaultTags: "tag:k8s"
  firewallMode: auto

# apiServerProxyConfig allows to configure whether the operator should expose
# Kubernetes API server.
# https://tailscale.com/kb/1437/kubernetes-operator-api-server-proxy
apiServerProxyConfig:
  mode: "false" # "true", "false", "noauth"

