---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: influxdb2-admin
  namespace: telegraf
spec:
  encryptedData:
    admin-password: AgBJcZ1xj4yUhv+8dmpXczKZiV3fLIWdpj5uU+CfZMZPhNkMy8xdMoeGhiADW78/5T11lJWMPwRp164dBvpK0cajeVMNLX3iZRiDO9xlXD+HqXbws9aqFDw2i7A71JyWywX8Natg0SMNhqgiCgu9Xt5XZxlNi5PQgUmGq9v3+iKP10ILmq/vtmJUqoOvf3gB/oSftYlWnSmsvpEmVQR8kvrQdcTkZekGodwmaJDEIN9v7J6tcrc+/axK5AMOsOQyS23gxix6QkkSH0PazzJ9TjxcIRgWvxgGz+nxstU+s7eyIKCz2icPa1fSrFcdySeQfQdA7nw3eDvu03TSPsbkPSXJ9J1Tm3yZleTcyKh6yeYWt4AAKqaOygpnS9hcgY0XgIyqZlyHkmCOtORrOMImc1HHjsZtKAJyQSxikKttxqg5s5N0N0iAQVIi9OhV8Ki3NF3Pnt2osr/ehKvfBPIATR+Nmb6F1zHi0VGKrXkxoBF88Q3MYMNQP8FH4Cvd3nEhPG/LGEoGFh45/o6rqOQbRdRM/KuUshLcFH7jLZ8567Y094GYXgYqwpYCtihdq9UmSC5h+5nHsN2tHmE5aBzn69ZVt7b47/qbJd9j8yexgj0o/sJGrF/4FO5eRnvfhnE1zK8wAGg9ciUgraDi1V7KY5G9M+ILbYt2OIjnrsArqEPmrZHzam8fY7JQXS2O+IabMSR6cJmkOpQ7pT20vK/tge84sSLVXes5pBmolcLKdBw=
    admin-token: AgCOoKGfa3UaOiupUQLvG+dLc+ULXAPSMm6nAQsyRY0dlazhr9/Bke8SvV2TQ8UmK5cDN7AjoGnd4zG8FwfqKmxNrj8kB9kIaYgYXcs2B32Cmk/Pz3hOcIhu4nxztaVfIv5Tx+Qpku0QifJ61SS9G9KWF54cyjCvYC0OLpwPXf5fuJl00I3SfN9uRX0kM042O2lkCfWryPRcgdusVR5v1u6cDxGyahi4FOo/Tcede+FHWSdaXO/v/uSGzkasNafZJqnuXBmHpqKPgknzSq7/PxTXu6valj+rHiqUkbYsvR5hb7G+LTf5/KyXNcDSwsdVt36tQ2fkZ+w47xTkhOPMR+4L34RV5OEii53MV2q3za+y+j6peKn0OQxqPZwikBkNSHU32nKgQMm93DI33v3sn3y2bHzxBb+LqtdoGddDk26wanc6/B+29ayfCBnlEWham/tzOZyhWKs9MbDgIDpvcKUJOagPJ7CZsqoIO4W3JaVdcEKBEb5r34Q9fJTGx3x9SkcUsWT++qB1anb93GGLhpqDkov8yiKJE3n9Gj+8H3U2rf9q5nAcceFjDRGiG2Tvj2RzaQ6qwY+mS3k9JiETe3rLhG+QqUOlfK9Qdm4vWq/xFnuxtSpzuFqQvS/O1WzL94kY2Cl6S16wwXHS6wnsW74zZ70kQWlR4C1fHe4PYZLV6l//9Omn3+i/gDPaRAWEn+EfcjwBzGUeB6diuq3ouYjwbmIn/SrLr5DV9Ojex9npxmPs0A46S7Fs+s1xvb8+lwRdZpnyeLZkQ0qPsObHz0xYfAr5b2Pl/CK367Ck9xy5n5dSYsH7z1F/
  template:
    metadata:
      name: influxdb2-admin
      namespace: telegraf
    type: Opaque
