---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: influxdb2-admin
  namespace: telegraf
spec:
  encryptedData:
    admin-password: AgAbR7KUePEJBIp85EYVYuYjQobCfVJVxxx2eYP2Hn2/0tZJsV+1UzVHICXdfV1zmovtu3cXoYrffpoc8otSSiMyVO9xyhvcRO95OchZpImc1Mtr9qEqO8qxRNBP8+nQp9o5eDqagOt0u8K06viQJ5GCmaYoAeVOni6sGvRXyG0HKGIunW/FQ+zql/Dil5n6UJ722tiK03PPCKIas8DEvaF4C3xISJBYRg2kSw5Loj8whWwpzcoMJISPBl0mdzi940U3zPBWk+kJwnVK+QHVTyEgMaxcRUaQKJoLRJCfrogAkgBqyzQuGKwrUV8SXbkFHb5FgjYAubaFjUo6Ec7nMUVQYq5MqVJdWfB04fcR4o+yeImeYy7pJUQ5I1PuMAnuMjoFAvPYkLXXuNFZaMIMMjOYU7xylUY24hXiEECpOHRAKXXT0eyVKjhAgFI6+FAjOKUf79ARP5nSvMQ1+NI8jWB8GXpcmqQ55Ff0wuqmV0sanWnNCnUVsRSa1hMmDdt1OtUE1c4GFFJNTWt6mQDAKM6yZfAw42hvKDD9/LrGIxu+m/4+n5zjmLAK+SaHKHzsGX5jWcqWCGBjJZG+SJ9L+pt1vsTN8Z9E7sxp4xMSfAovTqX+R4u/mcWSjmT06FCMzps0htY5ze/3pFc0TvvEt8FARp/se4zI7Yu7ycBG2N8RFFqpoOjM2rHwKf4QMY6B+gqQV9GbRRvoB1TVi91pJtbgUEWvt8PhueodhbSxG44=
    admin-token: AgAdbNa87qUBtPIAQT8O39qBIqWrH1DZIodWzsmbtrN1vOtuNQIKKSqf/PP8kcEqh8lcanqqemFnI/FfsnMNb7OmKDnBVF9mVEpgMAcLUhYeDC8tGDWP/tBjl6tsPSd1QwDzeS6rlmgBV2AKZJi2EVKkDzEOEDzWK2UPUAsmxY0Wey/DhjG2WE1R0jvVdqfpq2pFBrUxuTXSAJG+zyhEGG7YYITPHKF3brZ3vkzfym4tfEy7YVhuqwfhlOF4jZqXWiTy7WTqUmakoXrtarycDJyhm9+KbKhwFymg7sDTxq8sitIOFviYIFmeEmMVZ3a6AHiBFHSDwrHqjZAeE6OL7+nQKd7n6Zx7pY898E6AzVLmEy1k4UkwhHZSR2aYBK6dcMjaUZu6t7qIR/cXsO/KgPwuwjCWkKSXWFXBufm+i1lu3wi4+bsZ6lmsAIQfVnc1+dRoStrl5F5up6VZuORPAKFprEImr+C2PHaojJS2YK97kdR/VhzF9REzB03BQZ4ssKrXCr2tB3Afem2F3WF5TVlcrVIZkQUTKT4Y18EyIyJTjYpkSX6v2ikkc061leiFG1oBuI+Lf2/kQELkaMTSjuDkXcIXHPqAv6LTNLW8O5AF+HwYRctseSs8hm+vVLm77ET/X+t0POZR+ms/07s84iHMDgjkhH0wWXhtnk7ovOngTMV330eDSFPgH/0VYoYXSy3TuPcsjtv/eMijs2vqmnJ+isIjeguP12swnYaUQk+OTWY63FpDkw/zL4mlzPyW4RjFk0AJQfMnjBVxHNehZ/sL
  template:
    metadata:
      name: influxdb2-admin
      namespace: telegraf
    type: Opaque
