mlflow:
  image:
    debug: false
  tracking:
    auth:
      enabled: true
      username: admin
      password: "admin"
      flaskServerSecretKey: "secret"
    service:
      type: ClusterIP
    ingress:
      enabled: true
      hostname: mlflow.friis-jespersen.dev 
      tls: true
      extraTls:
        - hosts:
            - mlflow.friis-jespersen.dev
          secretName: friisjespersen-com-tls

  resources:
    requests:
      cpu: 100m
      memory: 1Gi 
    limits:
      cpu: 300m
      memory: 2Gi 


  postgresql:
    enabled: true
    auth:
      username: bn_mlflow
      password: "admin"
    networkPolicy:
      enabled: false

  minio:
    enabled: true
    auth:
      rootUser: admin
      rootPassword: "123456789"
