apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: wg-infisical-secret
spec:
  hostAPI: http://infisical.192.168.0.36.nip.io/api
  syncConfig:
    resyncInterval: 60s
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: homelab-iu-u6
        envSlug: prod
        secretsPath: /
  managedKubeSecretReferences:
    - secretName: wg-infisical-secret
      secretNamespace: media
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true
