apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/terrorbollen/homelab
    targetRevision: HEAD
    path: charts/media-server
    helm:
      releaseName: media
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
