apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/terrorbollen/homelab
    targetRevision: HEAD
    path: charts/isak.friis-jespersen
    helm:
      releaseName: portfolio
  destination:
    server: https://kubernetes.default.svc
    namespace: isakfriis-jespersen
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
