---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAnFzbtkXa4P+HMam3UuNm/PEd65BG1PY1PUjgXxjaEIJ3v4n836W4V/5SIX+cDcSL91J0Na00CUC6pWnVprc+66tfvI9kCQ0E8r4VcC/p4jZqQXN6UncSXkjeqMOFr9mkDlyMryi+4189Sm41pe4xp5O62306UW9ZDzfMzvk/1qP1DSJxxDXq65db4ZiGP1Cq3RG5u+JD4TgM5G9Cf4EQRMoD7OkrNddkC4v7HYu2X62Nw9KkkfvLm+vIJQlIy5DQZNBJ3VHmHWHgp7Zd2i5veTf9rSEUTm0oEPIZeD4jBte4vfXWB4oXnYUl+EAm+jLUUCRb1aH8UB16I1HeYqF4/UT8ZSAXF63Oyk2vazNnwh2J58kL2LeMgeNPtpsbVyZuN2H4tw9r1OOHZKhaFBOSM1ar9VqonDQNvUs8gfryM/FjhdXxR4XvWUlBrD5zSdDgRxmPgn2/g1McIbkuY8KLl2S4fAkp79wxx8HBP8hqgUWNbkn2uori4DU6aR2aCS1tQxCZ+B7YhZF+/HC3EbMcjZ32AE1B2OhBr4BuQjiQ3WGyri4EKWxq1EtthMrhXPJNOHgZRUakWeLzLEtP9mREvqimX4eG56ufJsGwqUa5ctgvBMuX8OFUb9zu1eFA4HUUOOsbxCwFnQndGpsqZKAqAfTNF22sOdSCqzykPJGIICUFwQngkGKcrkSb1sWZhsYZPUIB9pNB8Yzh9xfaawB4qzFxwcVdYX3chE8JeHfMO
    admin-user: AgC582nzvPuW4J91RJkezY1hWHIE7DHfed0NmxQZ3x85EXKulYZ9APr3cAQfnVTKTCjLXEKim72TnT//5fnpiEdPCCIBnr9npGtbXVxOsyqHbBP7kIwWSeLP08j2DboTtVpmrJ/I8F/Qq1BV4KeXQYoktZmsO2A2hFnebLhiuVFk/jrfS05L8eDaVi/5/k+eGCwm7zDXjHJK+tf7EIyJbSQfJIH9eLl3WlIosDabjNZe+YIAMLd2XOoiVHMvE/D8cxbij0BzID9PW3ONxTJO/bKmYd52+VK2E30NJ8z7fLxZVCkF7+53Ys4TMdERt1Yusm28x0eiXJML4f7+ZCLxOqkvE0t1gTbse02kmkWQtzSf/a3hoJMYrirhTJ8MLBawiXKuejuMysjUeodQzN15DtI5BqPuDC/oNwNfjtX6sxsvE0eQm5f1uvRdBcbC5LSuHXbQDWRL3ODtu3cMKFZtzRu8685cqve5oFsB8zpo9NKM8gleYTT/2c9y0IWJFsoUAKwEk9HFIAYSYoGPM3UNUku9UTt6z01jEq/uQtJRqcGeeExZTnEowf/QBWnkIQfrpt0zXEavZ90ZY7XsseIWBQITM6vCKRlCBgNjiSjru0gZ9pG6eI8akI683iwIAs5ZaSzjZsVZ485ELYouC6al1xv4UoXiwGy48em3z+wa4f00XQHCiLeTii4DnbUEX5hmTol4c5jJMg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
