apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ .Release.Name }}-ingress"
  annotations:
    kubernetes.io/ingress.class: traefik 
spec:
  rules:
    - host: {{ .Values.ingress.host | default (printf "media.%s.nip.io" .Values.ingress.ip) }}
      http:
        paths:
          - path: "/transmission"
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-transmission-openvpn"
                port:
                  number: 80
          - path: "/bazarr"
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-bazarr"
                port:
                  number: 80
          - path: "/sonarr"
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-sonarr"
                port:
                  number: 80
          - path: "/radarr"
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-radarr"
                port:
                  number: 80
          - path: "/prowlarr"
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-prowlarr"
                port:
                  number: 80
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-emby"
                port:
                  number: 80
